//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OPERADB : DbContext
    {
        public OPERADB()
            : base("name=OPERADB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<tipo_documento> tipo_documento { get; set; }
        public virtual DbSet<parametro> parametro { get; set; }
        public virtual DbSet<orden_servicio> orden_servicio { get; set; }
        public virtual DbSet<oficina> oficina { get; set; }
        public virtual DbSet<ubicacion_geografica> ubicacion_geografica { get; set; }
        public virtual DbSet<gestion> gestion { get; set; }
        public virtual DbSet<cartero> cartero { get; set; }
        public virtual DbSet<destinatario> destinatario { get; set; }
        public virtual DbSet<manifiesto_entrega> manifiesto_entrega { get; set; }
        public virtual DbSet<paquete> paquete { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<evento_orden_servicio> evento_orden_servicio { get; set; }
        public virtual DbSet<usuario_contrato> usuario_contrato { get; set; }
        public virtual DbSet<proceso_tmp> proceso_tmp { get; set; }
        public virtual DbSet<lista_manifiesto> lista_manifiesto { get; set; }
        public virtual DbSet<entrega> entrega { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<suceso> suceso { get; set; }
        public virtual DbSet<asesor_comercial> asesor_comercial { get; set; }
    
        public virtual ObjectResult<SPR_CONSULTA_USUARIO_CONTRATO_Result> SPR_CONSULTA_USUARIO_CONTRATO(Nullable<int> opcion, Nullable<int> id_usuario, string numero_identificacion, string nm_cliente)
        {
            var opcionParameter = opcion.HasValue ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var numero_identificacionParameter = numero_identificacion != null ?
                new ObjectParameter("numero_identificacion", numero_identificacion) :
                new ObjectParameter("numero_identificacion", typeof(string));
    
            var nm_clienteParameter = nm_cliente != null ?
                new ObjectParameter("nm_cliente", nm_cliente) :
                new ObjectParameter("nm_cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_CONSULTA_USUARIO_CONTRATO_Result>("SPR_CONSULTA_USUARIO_CONTRATO", opcionParameter, id_usuarioParameter, numero_identificacionParameter, nm_clienteParameter);
        }
    
        public virtual ObjectResult<SPR_CONSULTA_UBICACIONES_GEOGRAFICAS_Result> SPR_CONSULTA_UBICACIONES_GEOGRAFICAS(Nullable<int> opcion)
        {
            var opcionParameter = opcion.HasValue ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_CONSULTA_UBICACIONES_GEOGRAFICAS_Result>("SPR_CONSULTA_UBICACIONES_GEOGRAFICAS", opcionParameter);
        }
    
        public virtual ObjectResult<SPR_GENERAR_COD_MANIFIESTO_ENTREGA_Result> SPR_GENERAR_COD_MANIFIESTO_ENTREGA(Nullable<int> id_oficina)
        {
            var id_oficinaParameter = id_oficina.HasValue ?
                new ObjectParameter("id_oficina", id_oficina) :
                new ObjectParameter("id_oficina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_GENERAR_COD_MANIFIESTO_ENTREGA_Result>("SPR_GENERAR_COD_MANIFIESTO_ENTREGA", id_oficinaParameter);
        }
    
        public virtual int SPR_INSERTAR_LISTA_MANIFIESTO(Nullable<int> iD_MANIFIESTO, Nullable<System.Guid> iD_PROCESO, Nullable<int> oPCION)
        {
            var iD_MANIFIESTOParameter = iD_MANIFIESTO.HasValue ?
                new ObjectParameter("ID_MANIFIESTO", iD_MANIFIESTO) :
                new ObjectParameter("ID_MANIFIESTO", typeof(int));
    
            var iD_PROCESOParameter = iD_PROCESO.HasValue ?
                new ObjectParameter("ID_PROCESO", iD_PROCESO) :
                new ObjectParameter("ID_PROCESO", typeof(System.Guid));
    
            var oPCIONParameter = oPCION.HasValue ?
                new ObjectParameter("OPCION", oPCION) :
                new ObjectParameter("OPCION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPR_INSERTAR_LISTA_MANIFIESTO", iD_MANIFIESTOParameter, iD_PROCESOParameter, oPCIONParameter);
        }
    
        public virtual ObjectResult<SPR_CONSULTA_MANIFIESTO_Result> SPR_CONSULTA_MANIFIESTO(Nullable<int> oPCION, Nullable<int> iD_MANIFIESTO)
        {
            var oPCIONParameter = oPCION.HasValue ?
                new ObjectParameter("OPCION", oPCION) :
                new ObjectParameter("OPCION", typeof(int));
    
            var iD_MANIFIESTOParameter = iD_MANIFIESTO.HasValue ?
                new ObjectParameter("ID_MANIFIESTO", iD_MANIFIESTO) :
                new ObjectParameter("ID_MANIFIESTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_CONSULTA_MANIFIESTO_Result>("SPR_CONSULTA_MANIFIESTO", oPCIONParameter, iD_MANIFIESTOParameter);
        }
    
        public virtual ObjectResult<SPR_CONSULTA_EVENTOS_Result> SPR_CONSULTA_EVENTOS(Nullable<int> oPCION, Nullable<System.Guid> iDENTIFICADOR_PAQUETE)
        {
            var oPCIONParameter = oPCION.HasValue ?
                new ObjectParameter("OPCION", oPCION) :
                new ObjectParameter("OPCION", typeof(int));
    
            var iDENTIFICADOR_PAQUETEParameter = iDENTIFICADOR_PAQUETE.HasValue ?
                new ObjectParameter("IDENTIFICADOR_PAQUETE", iDENTIFICADOR_PAQUETE) :
                new ObjectParameter("IDENTIFICADOR_PAQUETE", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_CONSULTA_EVENTOS_Result>("SPR_CONSULTA_EVENTOS", oPCIONParameter, iDENTIFICADOR_PAQUETEParameter);
        }
    
        public virtual ObjectResult<SPR_CONSULTA_ORDENES_SERVICIO_Result> SPR_CONSULTA_ORDENES_SERVICIO(Nullable<int> opcion, Nullable<int> id_usuario, Nullable<int> orden_id)
        {
            var opcionParameter = opcion.HasValue ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(int));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var orden_idParameter = orden_id.HasValue ?
                new ObjectParameter("orden_id", orden_id) :
                new ObjectParameter("orden_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_CONSULTA_ORDENES_SERVICIO_Result>("SPR_CONSULTA_ORDENES_SERVICIO", opcionParameter, id_usuarioParameter, orden_idParameter);
        }
    
        public virtual ObjectResult<SPR_CONSULTA_ENVIO_GUIAS_Result> SPR_CONSULTA_ENVIO_GUIAS(Nullable<int> oPCION, Nullable<int> iD_ORDEN)
        {
            var oPCIONParameter = oPCION.HasValue ?
                new ObjectParameter("OPCION", oPCION) :
                new ObjectParameter("OPCION", typeof(int));
    
            var iD_ORDENParameter = iD_ORDEN.HasValue ?
                new ObjectParameter("ID_ORDEN", iD_ORDEN) :
                new ObjectParameter("ID_ORDEN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_CONSULTA_ENVIO_GUIAS_Result>("SPR_CONSULTA_ENVIO_GUIAS", oPCIONParameter, iD_ORDENParameter);
        }
    
        public virtual ObjectResult<string> SPR_CONSULTA_CREDENCIALES(Nullable<int> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SPR_CONSULTA_CREDENCIALES", iD_USUARIOParameter);
        }
    
        public virtual ObjectResult<SPR_ACTUALIZA_CREDENCIALES_Result> SPR_ACTUALIZA_CREDENCIALES(Nullable<int> iD_USUARIO, string cONTRASENIA)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var cONTRASENIAParameter = cONTRASENIA != null ?
                new ObjectParameter("CONTRASENIA", cONTRASENIA) :
                new ObjectParameter("CONTRASENIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_ACTUALIZA_CREDENCIALES_Result>("SPR_ACTUALIZA_CREDENCIALES", iD_USUARIOParameter, cONTRASENIAParameter);
        }
    
        public virtual ObjectResult<SPR_CONSULTA_ENVIO_Result> SPR_CONSULTA_ENVIO(Nullable<int> oPCION, string cODIGO_ENVIO, string cODIGO_ORDEN_SERVICIO, string dESTINATARIO, Nullable<int> uSUARIO, string fECHA1, string fECHA2, string gESTION, Nullable<int> iD_CLIENTE)
        {
            var oPCIONParameter = oPCION.HasValue ?
                new ObjectParameter("OPCION", oPCION) :
                new ObjectParameter("OPCION", typeof(int));
    
            var cODIGO_ENVIOParameter = cODIGO_ENVIO != null ?
                new ObjectParameter("CODIGO_ENVIO", cODIGO_ENVIO) :
                new ObjectParameter("CODIGO_ENVIO", typeof(string));
    
            var cODIGO_ORDEN_SERVICIOParameter = cODIGO_ORDEN_SERVICIO != null ?
                new ObjectParameter("CODIGO_ORDEN_SERVICIO", cODIGO_ORDEN_SERVICIO) :
                new ObjectParameter("CODIGO_ORDEN_SERVICIO", typeof(string));
    
            var dESTINATARIOParameter = dESTINATARIO != null ?
                new ObjectParameter("DESTINATARIO", dESTINATARIO) :
                new ObjectParameter("DESTINATARIO", typeof(string));
    
            var uSUARIOParameter = uSUARIO.HasValue ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(int));
    
            var fECHA1Parameter = fECHA1 != null ?
                new ObjectParameter("FECHA1", fECHA1) :
                new ObjectParameter("FECHA1", typeof(string));
    
            var fECHA2Parameter = fECHA2 != null ?
                new ObjectParameter("FECHA2", fECHA2) :
                new ObjectParameter("FECHA2", typeof(string));
    
            var gESTIONParameter = gESTION != null ?
                new ObjectParameter("GESTION", gESTION) :
                new ObjectParameter("GESTION", typeof(string));
    
            var iD_CLIENTEParameter = iD_CLIENTE.HasValue ?
                new ObjectParameter("ID_CLIENTE", iD_CLIENTE) :
                new ObjectParameter("ID_CLIENTE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_CONSULTA_ENVIO_Result>("SPR_CONSULTA_ENVIO", oPCIONParameter, cODIGO_ENVIOParameter, cODIGO_ORDEN_SERVICIOParameter, dESTINATARIOParameter, uSUARIOParameter, fECHA1Parameter, fECHA2Parameter, gESTIONParameter, iD_CLIENTEParameter);
        }
    
        public virtual ObjectResult<SPR_ACT_ULTIMO_EVENTO_Result> SPR_ACT_ULTIMO_EVENTO(string cODIGO_ENVIO, Nullable<int> oPCION, string uSUARIO)
        {
            var cODIGO_ENVIOParameter = cODIGO_ENVIO != null ?
                new ObjectParameter("CODIGO_ENVIO", cODIGO_ENVIO) :
                new ObjectParameter("CODIGO_ENVIO", typeof(string));
    
            var oPCIONParameter = oPCION.HasValue ?
                new ObjectParameter("OPCION", oPCION) :
                new ObjectParameter("OPCION", typeof(int));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPR_ACT_ULTIMO_EVENTO_Result>("SPR_ACT_ULTIMO_EVENTO", cODIGO_ENVIOParameter, oPCIONParameter, uSUARIOParameter);
        }
    }
}
