//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class destinatario
    {
        public int id { get; set; }
        public Nullable<System.Guid> identificador_paquete { get; set; }
        public string destinatario1 { get; set; }
        public Nullable<int> provincia { get; set; }
        public Nullable<int> canton { get; set; }
        public Nullable<int> parroquia { get; set; }
        public string calle_principal { get; set; }
        public string numero { get; set; }
        public string interseccion { get; set; }
        public string referencia { get; set; }
        public string codigo_postal { get; set; }
        public Nullable<int> latitud { get; set; }
        public Nullable<int> longitud { get; set; }
        public string telefono { get; set; }
        public string correo_electronico { get; set; }
    
        public virtual paquete paquete { get; set; }
    }
}
