//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrega
    {
        public int id { get; set; }
        public Nullable<System.Guid> identificador_paquete { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string fecha_entrega { get; set; }
        public string hora_entrega { get; set; }
        public string receptor { get; set; }
        public string identificacion_receptor { get; set; }
        public string observacion { get; set; }
        public Nullable<int> locacion_entrega { get; set; }
        public Nullable<int> control_dir_entrega { get; set; }
        public string direccion_actualizada { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> id_oficina { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string registro_fotografico { get; set; }
    
        public virtual paquete paquete { get; set; }
    }
}
