//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class manifiesto_entrega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public manifiesto_entrega()
        {
            this.lista_manifiesto = new HashSet<lista_manifiesto>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_cartero { get; set; }
        public string codigo_manifiesto { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_oficina { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> secuencia { get; set; }
    
        public virtual cartero cartero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lista_manifiesto> lista_manifiesto { get; set; }
    }
}
