//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orden_servicio()
        {
            this.paquete = new HashSet<paquete>();
            this.evento_orden_servicio = new HashSet<evento_orden_servicio>();
        }
    
        public int id { get; set; }
        public string codigo_orden_servicio { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_tipo_servicio { get; set; }
        public Nullable<System.DateTime> fecha_carga { get; set; }
        public Nullable<int> numero_registros_cargados { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> estado { get; set; }
        public string detalle { get; set; }
        public Nullable<System.DateTime> fecha_ultima_gestion { get; set; }
        public Nullable<int> id_usuario_ultima_gestion { get; set; }
        public Nullable<int> id_oficina_carga { get; set; }
        public string id_provincia_carga { get; set; }
        public string id_canton_carga { get; set; }
        public Nullable<int> id_contrato { get; set; }
    
        public virtual servicio servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paquete> paquete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento_orden_servicio> evento_orden_servicio { get; set; }
    }
}
