//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class paquete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paquete()
        {
            this.destinatario = new HashSet<destinatario>();
            this.evento = new HashSet<evento>();
            this.lista_manifiesto = new HashSet<lista_manifiesto>();
            this.entrega = new HashSet<entrega>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public System.Guid identificador { get; set; }
        public string codigo_alterno { get; set; }
        public Nullable<decimal> peso { get; set; }
        public string seguro { get; set; }
        public string tipo_contenido { get; set; }
        public Nullable<decimal> monto_seguro { get; set; }
        public Nullable<decimal> alto { get; set; }
        public Nullable<decimal> ancho { get; set; }
        public Nullable<decimal> profundidad { get; set; }
        public Nullable<decimal> peso_volumentrico { get; set; }
        public Nullable<System.DateTime> fecha_evento_carga { get; set; }
        public Nullable<int> id_oficina_carga { get; set; }
        public Nullable<System.DateTime> fecha_ultimo_evento { get; set; }
        public Nullable<int> id_ultm_evento { get; set; }
        public Nullable<int> id_oficina_ultm_evento { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string guia_generada { get; set; }
        public string dato_adicional1 { get; set; }
        public string dato_adicional2 { get; set; }
        public Nullable<int> id_orden_servicio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<destinatario> destinatario { get; set; }
        public virtual orden_servicio orden_servicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<evento> evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lista_manifiesto> lista_manifiesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrega> entrega { get; set; }
    }
}
