//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro
    {
        public int id { get; set; }
        public string nm_descriptivo { get; set; }
        public string tipo { get; set; }
        public string valor1 { get; set; }
        public string valor2 { get; set; }
        public Nullable<int> valor3 { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
