//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro_configuracion
    {
        public int id { get; set; }
        public string grupo { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public string valor_max { get; set; }
        public string valor_html { get; set; }
        public string valor_clave { get; set; }
        public Nullable<int> valor_numerico { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> valor_decimal { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
