//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public int per_id { get; set; }
        public Nullable<int> per_tipo_documento { get; set; }
        public string per_numero_identificacion { get; set; }
        public string per_nombres { get; set; }
        public string per_apellidos { get; set; }
        public string per_telefono_convencional { get; set; }
        public string per_celular { get; set; }
        public string per_correo_electronico { get; set; }
        public Nullable<int> id_provincia { get; set; }
        public Nullable<int> id_canton { get; set; }
        public Nullable<int> id_parroquia { get; set; }
        public string direccion_domiciliaria { get; set; }
        public string direccion_trabajo { get; set; }
        public Nullable<int> per_casillero { get; set; }
        public string per_contrasenia { get; set; }
        public Nullable<int> per_codigo_confirmacion { get; set; }
        public Nullable<System.DateTime> fec_creacion { get; set; }
        public Nullable<System.DateTime> fec_modificacion { get; set; }
        public Nullable<int> usu_creacion { get; set; }
        public Nullable<int> usu_modificacion { get; set; }
        public Nullable<int> per_estado { get; set; }
    
        public virtual casillero_secuencia casillero_secuencia { get; set; }
    }
}
