//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicio()
        {
            this.orden_servicio = new HashSet<orden_servicio>();
        }
    
        public int id { get; set; }
        public string nm_servicio { get; set; }
        public string prefijo { get; set; }
        public Nullable<int> secuencia_inicial { get; set; }
        public Nullable<int> secuencia_actual { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden_servicio> orden_servicio { get; set; }
    }
}
