//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacion_geografica
    {
        public int id { get; set; }
        public string id_provincia { get; set; }
        public string id_canton { get; set; }
        public string id_parroquia { get; set; }
        public string nm_provincia { get; set; }
        public string nm_canton { get; set; }
        public string nm_parroquia { get; set; }
        public Nullable<bool> estado { get; set; }
    }
}
