//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_contrato
    {
        public int id { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_contrato { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual contrato contrato { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
